site_name: Lost Signal
docs_dir: docs
theme:
  name: material
  language: en

nav:
  - Home:
      - English: index_en.md
      - Français: index.md
  - Getting Started:
      - English: getting_started_en.md
      - Français: getting_started.md
  - Authoring Guide:
      - English: authoring_en.md
      - Français: authoring.md
  - Story Editor:
      - English: story_editor_en.md
      - Français: story_editor.md
  - Overview:
      - English: Product_Page_en.md
      - Français: Product_Page.md